package com.example.crochet3


enum class Screens(val route: String) {
    MAINACTIVITY("main"),
    CATEGORYSCREEN("categoriesScreen"),
    SEARCHPAGE("searchPage"),
    SUBSCREENSCATEGORIES("subscreensCategories"),
    FAVORITES("favorites"),
    PATTERNPAGE("patternPage"),
    TOOLS("tools"),
    APPINFO("appInfo"),
    HATS("hats"),
    SCARVES("scarves"),
    GLOVES("gloves"),
    SHAWLS("shawls"),
    BLANKETS("blankets"),
    BAGS("bags"),
    AMIGURUMI("amigurumi"),
    COASTERS("coasters"),
    SOCKS("socks"),
    DECOR("decor"),
    MISCELLANEOUS("miscellaneous"),
    ALL("all"),
}

data class CrochetPattern(
    val name: String,
    val newPattern: Boolean,
    val featured: Boolean,
    val difficulty: Difficulty,
    val hookSize: HookSize,
    val category: Category,
    val creatorname: String,
    val creatorlink: String,
    val imageResId: Int,
    val image2: Int,
    val image3: Int,
    val notes: String,
    val timeToComplete: String,
    val materials: String,
    val instructions: String,
) {
    fun doesMatchSearchQuery(query:String): Boolean {
        val matchingCombinations = listOf(
            name,
            "$category",
            creatorname,

        )
        return matchingCombinations.any {
            it.contains(query, ignoreCase = true)
        }
    }
}

enum class Difficulty {
    BEGINNER,
    EASY,
    INTERMEDIATE,
    HARD,
}

enum class Category {
    HATS,
    SCARVES,
    GLOVES,
    SHAWLS,
    BLANKETS,
    BAGS,
    AMIGURUMI,
    COASTERS,
    SOCKS,
    DECOR,
    MISCELLANEOUS,
}

enum class HookSize(val size: String) {
    TWOPOINTFIVE("2.5mm"),
    THREE("3.0mm"),
    THREEPOINTFIVE("3.5mm"),
    FOUR("4.0mm"),
    FOURPOINTFIVE("4.5mm"),
    FIVE("5.0mm"),
    FIVEPOINTFIVE("5.5mm"),
    SIX("6.0mm"),
    SIXPOINTFIVE("6.5mm"),
    SEVEN("7.0mm"),
    SEVENPOINTFIVE("7.5mm"),
    EIGHT("8.0mm"),
    EIGHTPOINTFIVE("8.5mm"),
    NINE("9.0mm"),
    NINEPOINTFIVE("9.5mm"),
    TEN("10.0mm")
}


val crochetPatterns = listOf(
    CrochetPattern(
        name = "Amigurumi",
        newPattern = true,
        featured = true,
        difficulty = Difficulty.EASY,
        hookSize = HookSize.EIGHTPOINTFIVE,
        category = Category.BLANKETS,
        creatorname = "Anonymous",
        creatorlink = "https://google.com",
        imageResId = R.drawable.amigurumi,
        image2 = R.drawable.a,
        image3 = R.drawable.a,
        notes= "",
        timeToComplete = "1 Hour",
        materials = "",
        instructions = "add instructions here add instructions here add instructions here add instructions here"),
    CrochetPattern(
        name = "Flower Hat 2",
        newPattern = true,
        featured = true,
        difficulty = Difficulty.HARD,
        hookSize = HookSize.FIVE,
        category = Category.HATS,
        creatorname = "Anonymous",
        creatorlink = "https://google.com",
        imageResId = R.drawable.b,
        image2 = R.drawable.b,
        image3 = R.drawable.b,
        notes= "",
        timeToComplete = "1 Hour",
        materials = "",
        instructions = "add instructions here add instructions here add instructions here add instructions here" ),
    CrochetPattern(
        name = "Stripe Hat",
        newPattern = true,
        featured = true,
        difficulty = Difficulty.INTERMEDIATE,
        hookSize = HookSize.EIGHTPOINTFIVE,
        category = Category.BLANKETS,
        creatorname = "Anonymous",
        creatorlink = "https://google.com",
        imageResId = R.drawable.c,
        image2 = R.drawable.c,
        image3 = R.drawable.c,
        notes= "",
        timeToComplete = "1 Hour",
        materials = "",
        instructions = "add instructions here add instructions here add instructions here add instructions here"),
    CrochetPattern(
        name = "Bunny Ears",
        newPattern = true,
        featured = false,
        difficulty = Difficulty.EASY,
        hookSize = HookSize.FIVE,
        category = Category.SCARVES,
        creatorname = "Anonymous",
        creatorlink = "https://google.com",
        imageResId = R.drawable.d,
        image2 = R.drawable.d,
        image3 = R.drawable.d,
        notes= "",
        timeToComplete = "1 Hour",
        materials = "",
        instructions = "add instructions here add instructions here add instructions here add instructions here" ),
    CrochetPattern(
        name = "Blanket",
        newPattern = true,
        featured = true,
        difficulty = Difficulty.EASY,
        hookSize = HookSize.FOUR,
        category = Category.SHAWLS,
        creatorname = "Anonymous",
        creatorlink = "https://google.com",
        imageResId = R.drawable.blanket,
        image2 = R.drawable.blanket,
        image3 = R.drawable.blanket,
        notes= "",
        timeToComplete = "1 Hour",
        materials = "",
        instructions = "add instructions here add instructions here add instructions here add instructions here"),
    CrochetPattern(
        name = "Pattern 14",
        newPattern = true,
        featured = true,
        difficulty = Difficulty.HARD,
        hookSize = HookSize.FIVE,
        category = Category.COASTERS,
        creatorname = "Anonymous",
        creatorlink = "https://google.com",
        imageResId = R.drawable.f,
        image2 = R.drawable.f,
        image3 = R.drawable.f,
        notes= "",
        timeToComplete = "1 Hour",
        materials = "",
        instructions = "add instructions here add instructions here add instructions here add instructions here" ),
    CrochetPattern(
        name = "Pattern 15",
        newPattern = true,
        featured = false,
        difficulty = Difficulty.INTERMEDIATE,
        hookSize = HookSize.SIX,
        category = Category.AMIGURUMI,
        creatorname = "Anonymous",
        creatorlink = "https://google.com",
        imageResId = R.drawable.g,
        image2 = R.drawable.g,
        image3 = R.drawable.g,
        notes= "",
        timeToComplete = "1 Hour",
        materials = "",
        instructions = "add instructions here add instructions here add instructions here add instructions here"),
    CrochetPattern(
        name = "Pattern 16",
        newPattern = true,
        featured = false,
        difficulty = Difficulty.INTERMEDIATE,
        hookSize = HookSize.FIVEPOINTFIVE,
        category = Category.SOCKS,
        creatorname = "Anonymous",
        creatorlink = "https://google.com",
        imageResId = R.drawable.b,
        image2 = R.drawable.b,
        image3 = R.drawable.b,
        notes= "",
        timeToComplete = "1 Hour",
        materials = "",
        instructions = "add instructions here add instructions here add instructions here add instructions here" ),
    CrochetPattern(
        name = "Pattern 17",
        newPattern = true,
        featured = false,
        difficulty = Difficulty.EASY,
        hookSize = HookSize.EIGHTPOINTFIVE,
        category = Category.BLANKETS,
        creatorname = "Anonymous",
        creatorlink = "https://google.com",
        imageResId = R.drawable.blanket,
        image2 = R.drawable.blanket,
        image3 = R.drawable.blanket,
        notes= "",
        timeToComplete = "1 Hour",
        materials = "",
        instructions = "add instructions here add instructions here add instructions here add instructions here"),
)