package com.example.crochet3
val crochetPatterns = listOf(
    CrochetPattern(
        name = "Amigurumi",
        difficulty = Difficulty.EASY,
        hookSize = HookSize.EIGHTPOINTFIVE,
        category = Category.BLANKETS,
        creatorname = "Anonymous",
        creatorlink = "https://google.com",
        imageResId = R.drawable.amigurumi,
        image2 = R.drawable.a,
        image3 = R.drawable.a,
        notes= "",
        timeToComplete = "1 Hour",
        materials = "",
        instructions = "add instructions here add instructions here add instructions here add instructions here"),
    CrochetPattern(
        name = "Flower Hat 2",
        difficulty = Difficulty.HARD,
        hookSize = HookSize.FIVE,
        category = Category.HATS,
        creatorname = "Anonymous",
        creatorlink = "https://google.com",
        imageResId = R.drawable.b,
        image2 = R.drawable.b,
        image3 = R.drawable.b,
        notes= "",
        timeToComplete = "1 Hour",
        materials = "",
        instructions = "add instructions here add instructions here add instructions here add instructions here" ),
    CrochetPattern(
        name = "Stripe Hat",
        difficulty = Difficulty.INTERMEDIATE,
        hookSize = HookSize.EIGHTPOINTFIVE,
        category = Category.BLANKETS,
        creatorname = "Anonymous",
        creatorlink = "https://google.com",
        imageResId = R.drawable.c,
        image2 = R.drawable.c,
        image3 = R.drawable.c,
        notes= "",
        timeToComplete = "1 Hour",
        materials = "",
        instructions = "add instructions here add instructions here add instructions here add instructions here"),
    CrochetPattern(
        name = "Bunny Ears",
        difficulty = Difficulty.EASY,
        hookSize = HookSize.FIVE,
        category = Category.SCARVES,
        creatorname = "Anonymous",
        creatorlink = "https://google.com",
        imageResId = R.drawable.d,
        image2 = R.drawable.d,
        image3 = R.drawable.d,
        notes= "",
        timeToComplete = "1 Hour",
        materials = "",
        instructions = "add instructions here add instructions here add instructions here add instructions here" ),
    CrochetPattern(
        name = "Blanket",
        difficulty = Difficulty.EASY,
        hookSize = HookSize.FOUR,
        category = Category.SHAWLS,
        creatorname = "Anonymous",
        creatorlink = "https://google.com",
        imageResId = R.drawable.blanket,
        image2 = R.drawable.blanket,
        image3 = R.drawable.blanket,
        notes= "",
        timeToComplete = "1 Hour",
        materials = "",
        instructions = "add instructions here add instructions here add instructions here add instructions here"),
    CrochetPattern(
        name = "Pattern 14",
        difficulty = Difficulty.HARD,
        hookSize = HookSize.FIVE,
        category = Category.COASTERS,
        creatorname = "Anonymous",
        creatorlink = "https://google.com",
        imageResId = R.drawable.f,
        image2 = R.drawable.f,
        image3 = R.drawable.f,
        notes= "",
        timeToComplete = "1 Hour",
        materials = "",
        instructions = "add instructions here add instructions here add instructions here add instructions here" ),
    CrochetPattern(
        name = "Pattern 15",
        difficulty = Difficulty.INTERMEDIATE,
        hookSize = HookSize.SIX,
        category = Category.AMIGURUMI,
        creatorname = "Anonymous",
        creatorlink = "https://google.com",
        imageResId = R.drawable.g,
        image2 = R.drawable.g,
        image3 = R.drawable.g,
        notes= "",
        timeToComplete = "1 Hour",
        materials = "",
        instructions = "add instructions here add instructions here add instructions here add instructions here"),
    CrochetPattern(name = "Pattern 16",         difficulty = Difficulty.INTERMEDIATE,    hookSize = HookSize.FIVEPOINTFIVE,     category = Category.SOCKS,          creatorname = "Anonymous",         creatorlink = "https://google.com",             imageResId = R.drawable.b,          image2 = R.drawable.b,          image3 = R.drawable.b,                     notes= "",        timeToComplete = "1 Hour",     materials = "",           instructions = "add instructions here add instructions here add instructions here add instructions here" ),
    CrochetPattern(name = "Pattern 17",         difficulty = Difficulty.EASY,            hookSize = HookSize.EIGHTPOINTFIVE,    category = Category.BLANKETS,       creatorname = "Anonymous",         creatorlink = "https://google.com",             imageResId = R.drawable.blanket,    image2 = R.drawable.blanket,    image3 = R.drawable.blanket,               notes= "",         timeToComplete = "1 Hour",  materials = "",           instructions = "add instructions here add instructions here add instructions here add instructions here"),
    CrochetPattern(name = "Pattern 18",         difficulty = Difficulty.HARD,            hookSize = HookSize.FIVE,              category = Category.DECOR,          creatorname = "Anonymous",         creatorlink = "https://google.com",             imageResId = R.drawable.c,          image2 = R.drawable.c,          image3 = R.drawable.c,                     notes= "",       timeToComplete = "1 Hour",   materials = "",          instructions = "add instructions here add instructions here add instructions here add instructions here" ),
    CrochetPattern(name = "Pattern 19",         difficulty = Difficulty.INTERMEDIATE,    hookSize = HookSize.EIGHTPOINTFIVE,    category = Category.BLANKETS,       creatorname = "Anonymous",         creatorlink = "https://google.com",             imageResId = R.drawable.a,          image2 = R.drawable.a,          image3 = R.drawable.a,                     notes= "",        timeToComplete = "1 Hour",   materials = "",          instructions = "add instructions here add instructions here add instructions here add instructions here"),
    CrochetPattern(name = "Pattern 20",         difficulty = Difficulty.INTERMEDIATE,    hookSize = HookSize.FIVE,              category = Category.HATS,           creatorname = "Anonymous",         creatorlink = "https://google.com",             imageResId = R.drawable.a,          image2 = R.drawable.a,          image3 = R.drawable.a,                     notes= "",          timeToComplete = "1 Hour",  materials = "",           instructions = "add instructions here add instructions here add instructions here add instructions here" ),
    CrochetPattern(name = "Pattern 1",          difficulty = Difficulty.EASY,            hookSize = HookSize.EIGHTPOINTFIVE,    category = Category.GLOVES,         creatorname = "Anonymous",         creatorlink = "https://google.com",             imageResId = R.drawable.blanket,    image2 = R.drawable.blanket,    image3 = R.drawable.blanket,               notes= "",          timeToComplete = "1 Hour",  materials = "",            instructions = "add instructions here add instructions here add instructions here add instructions here"),
    CrochetPattern(name = "Pattern 2",          difficulty = Difficulty.HARD,            hookSize = HookSize.SEVENPOINTFIVE,    category = Category.HATS,           creatorname = "Anonymous",         creatorlink = "https://google.com",             imageResId = R.drawable.b,          image2 = R.drawable.b,          image3 = R.drawable.b,                     notes= "",        timeToComplete = "1 Hour",   materials = "",            instructions = "add instructions here add instructions here add instructions here add instructions here" ),
    CrochetPattern(name = "Pattern 3",          difficulty = Difficulty.INTERMEDIATE,    hookSize = HookSize.EIGHTPOINTFIVE,    category = Category.BAGS,           creatorname = "Anonymous",        creatorlink = "https://google.com",             imageResId = R.drawable.b,          image2 = R.drawable.b,          image3 = R.drawable.b,                     notes= "",          timeToComplete = "1 Hour",  materials = "",           instructions = "add instructions here add instructions here add instructions here add instructions here"),
    CrochetPattern(name = "Pattern 4",          difficulty = Difficulty.EASY,            hookSize = HookSize.SEVEN,             category = Category.SCARVES,        creatorname ="Anonymous",         creatorlink = "https://google.com",             imageResId = R.drawable.b,          image2 = R.drawable.b,          image3 = R.drawable.b,                     notes= "",           timeToComplete = "1 Hour",   materials = "",          instructions = "add instructions here add instructions here add instructions here add instructions here" ),
    CrochetPattern(name = "Pattern 5",          difficulty = Difficulty.EASY,            hookSize = HookSize.THREE,             category = Category.SHAWLS,         creatorname = "Anonymous",         creatorlink = "https://google.com",             imageResId = R.drawable.blanket,    image2 = R.drawable.blanket,    image3 = R.drawable.blanket,               notes= "",          timeToComplete = "1 Hour",    materials = "",          instructions = "add instructions here add instructions here add instructions here add instructions here"),
    CrochetPattern(name = "Pattern 6",          difficulty = Difficulty.HARD,            hookSize = HookSize.FIVE,              category = Category.COASTERS,       creatorname = "Anonymous",        creatorlink = "https://google.com",             imageResId = R.drawable.c,          image2 = R.drawable.c,          image3 = R.drawable.c,                     notes= "",            timeToComplete = "1 Hour", materials = "",           instructions = "add instructions here add instructions here add instructions here add instructions here" ),
    CrochetPattern(name = "Pattern 7",          difficulty = Difficulty.INTERMEDIATE,    hookSize = HookSize.SIXPOINTFIVE,      category = Category.AMIGURUMI,      creatorname = "Anonymous",         creatorlink = "https://google.com",             imageResId = R.drawable.a,          image2 = R.drawable.a,          image3 = R.drawable.a,                     notes= "",           timeToComplete = "1 Hour",  materials = "",          instructions = "add instructions here add instructions here add instructions here add instructions here"),
    CrochetPattern(name = "Pattern 8",          difficulty = Difficulty.INTERMEDIATE,    hookSize = HookSize.EIGHT,             category = Category.SOCKS,          creatorname = "Anonymous",         creatorlink = "https://google.com",             imageResId = R.drawable.b,          image2 = R.drawable.b,          image3 = R.drawable.b,                     notes= "",           timeToComplete = "1 Hour",   materials = "",          instructions = "add instructions here add instructions here add instructions here add instructions here" ),
    CrochetPattern(name = "Pattern 9",          difficulty = Difficulty.EASY,            hookSize = HookSize.EIGHTPOINTFIVE,    category = Category.BLANKETS,       creatorname = "Anonymous",         creatorlink = "https://google.com",             imageResId = R.drawable.blanket,    image2 = R.drawable.blanket,    image3 = R.drawable.blanket,               notes= "",           timeToComplete = "1 Hour",  materials = "",          instructions = "add instructions here add instructions here add instructions here add instructions here"),
    CrochetPattern(name = "Pattern 10",         difficulty = Difficulty.HARD,            hookSize = HookSize.NINE,              category = Category.DECOR,          creatorname = "Anonymous",         creatorlink = "https://google.com",             imageResId = R.drawable.g,          image2 = R.drawable.g,          image3 = R.drawable.g,                     notes= "",           timeToComplete = "1 Hour",   materials = "",          instructions = "add instructions here add instructions here add instructions here add instructions here" ),
    CrochetPattern(name = "Pattern 11",         difficulty = Difficulty.INTERMEDIATE,    hookSize = HookSize.EIGHTPOINTFIVE,    category = Category.BLANKETS,       creatorname = "Anonymous",        creatorlink = "https://google.com",             imageResId = R.drawable.g,          image2 = R.drawable.g,          image3 = R.drawable.g,                     notes= "",          timeToComplete = "1 Hour", materials = "",            instructions = "add instructions here add instructions here add instructions here add instructions here"),
    CrochetPattern(name = "Pattern 12",         difficulty = Difficulty.INTERMEDIATE,    hookSize = HookSize.TEN,               category = Category.MISCELLANEOUS,  creatorname = "Anonymous",        creatorlink = "https://google.com",             imageResId = R.drawable.g,          image2 = R.drawable.g,          image3 = R.drawable.g,                     notes= "",          timeToComplete = "1 Hour",  materials = "",           instructions = "add instructions here add instructions here add instructions here add instructions here" ),
    )